[project]
name = "tli"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "rich",
    "python-dotenv",
    "ruff",
]

[dependency-groups]
dev = [
    "pytest",
    "mypy",
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[tool.ruff]
line-length = 100


[tool.mypy]
namespace_packages = false
check_untyped_defs = true
